@host = http://localhost:5224

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjJiNDI3Zi05YmU2LTQ1OWUtOWNmYS0yNmQ5MmUxZTUyNzkiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImVtYWlsQHZhbGlkLmNvbSIsImp0aSI6Ijk2MjFjOTkzLTk2MGEtNDVlMy1hYzU0LTYzZDQ5NTM2NGNhNCIsImV4cCI6MTY5OTY5NzQwMywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.s8N0C0ZufVj3uHpqmF4pnVK0RN9UwznKJ8zlsHC1JHw

